### ISSUE TITLE
Expose `TestCase` struct publicly for reuse

### ISSUE THREAD

**Issue by evforde** [frondeus/test-case#113]
Hey team!

Love the work you've done - we use `#[test_case]` all the time.

- What I'm trying to do

I'm hoping to expand on this crate for a self-rolled project - we've created a shorthand util to automatically set up and inject a db connection as an argument into our unit tests that talk to a database:

```
#[db_test]
fn test_my_thing(conn: &mut TestPgConn) {
  // Do something with `conn`
}
```

I'm looking to extend our utils to have similar syntax to `test_case`, allowing us to parameterize tests with our connection injected:

```
#[db_test(1 => 2)]
#[db_test(2 => 3)]
fn test_my_thing(conn: &mut TestPgConn, input: i32) -> i32 {
  add_one_inside_the_db_for_fun(conn, input).unwrap()
}
```

- How can `test_case` help?

It would be great to not recreate the logic to parse the args `TokenStream` in our own proc macro. I'd love to reuse the [`TestCase`](https://github.com/frondeus/test-case/blob/v2.2.0/crates/test-case-macros/src/test_case.rs#L11) struct, but it's not currently publicly exported.

How would you feel about exposing this `TestCase` struct publicly, perhaps behind a feature?

Thanks for your help - appreciate it!

**Comment by luke-biel** [comment]
I have no issue with test case exposing `TestCase` struct publicly. We simply didn't do that because of limitation of `proc_macro` crates, which can only export procedural macros. Most likely if you'd like to implement that it would require splitting `test_case_macros` into two separate crates, one exposing structures and other providing proc macro implementations.

Contributions are welcome :)
