### ISSUE TITLE
Testing for NaN

### ISSUE THREAD

**Issue by leonskidev** [frondeus/test-case#73]
Thanks for the awesome crate!

I was wondering if there was any way to go about testing `NaN` value equality? I've tried a few ideas to no success (unless I went about them wrong), such as using the `hamcrest2` support.

If this isn't possible at the moment then I already have a workaround using regular tests, but maybe it could be supported somehow in the future.

**Comment by luke-biel** [comment]
Without code snippet it's hard for me to help you with your exact problem, but I'm assuming you have something like this:
```rust
#[test_case(input => 1.0)]
#[test_case(input2 => NaN)]
fn test(input: X) -> f64 {
	stuff...
}
```
`NaN == Nan` equals ta false by design, it's not even a rust thing. I don't see an easy way to do this in single function, not with current syntax of `test_case`. You'd have to be able to provide custom assertion, which would for this `NaN` case validate it via `!value.is_nan()`. Custom assertions aren't supported within the lib though.
What I would try to do is to separate this into two functions, one that tests "correct" outcomes and one that checks for `NaN` and returns a boolean.

```rust
#[test_case(input => 1.0)]
fn test(input: X) -> f64 {
	stuff...
}
```

```rust
#[test_case(input2 => true)]
fn test(input: X) -> bool {
	(stuff that returns NaN...).is_nan()
}
```

**Comment by leonskidev** [comment]
> Without code snippet it's hard for me to help you with your exact problem.

Thanks, I knew I forgot to do something when posting the issue. (whoops)

> `NaN == NaN` resolves to false by design, it's not even a rust thing.

Yep, I should have made my understanding of this clearer. (whoops)

I was more so wondering if a feature was in the works for these sorts of tests, or for a possible future idea? If not then it's all good, just couldn't find an issue referring to that was all.

**Comment by luke-biel** [comment]
Understood.
Well, there were plans for mentioned custom assertions https://github.com/frondeus/test-case/issues/31, but we've never came to an agreement on how they should look like, so the idea sits there waiting for a better time.

**Comment by leonskidev** [comment]
Ah, coolio. Thanks for the help and information anyway. I look forward to using this crate in more projects.
